USE EXAMCINFO2022

---------------Pregunta 2-----------------------

Create Table Personas
(
    id_Persona int Identity(1,1),
    Nombre varchar(30),
    Celular char(9)
)
Create Table Cursos
(
    id_Curso int Identity(1,1),
    Descripcion varchar(30)
)
Create Table Notas
(
    id_Persona int Not NULL,
    id_Curso int Not NULL,
    Nota int
)

------------------------------------------------

--pregunta 2.1--
ALTER TABLE PERSONAS 
ADD PRIMARY KEY (ID_PERSONA)
EXEC SP_HELP PERSONAS

ALTER TABLE CURSOS 
ADD PRIMARY KEY (ID_CURSO)
EXEC SP_HELP CURSOS
--pregunta 2.2--

ALTER TABLE PERSONAS ALTER COLUMN CELULAR INT NOT NULL
EXEC SP_HELP PERSONAS

ALTER TABLE PERSONAS 
ADD CONSTRAINT CELULARCHK CHECK (LEN(CELULAR) = 9)

EXEC SP_HELP PERSONAS
INSERT INTO PERSONAS VALUES ('123', 912312312)
INSERT INTO PERSONAS VALUES ('Joan', 955255355)
INSERT INTO PERSONAS VALUES ('Manuel', 980)
SELECT * FROM PERSONAS
--pregunta 2.3---
SELECT * FROM CURSOS
ALTER TABLE CURSOS
ADD CONSTRAINT DF_DESCRIPTION DEFAULT 'Por Definir' FOR [DESCRIPCION]

INSERT INTO CURSOS VALUES (null)         --NOT WORKING DEFAULT--
INSERT INTO CURSOS VALUES ('TEST')       --NOT WORKING DEFAULT--
INSERT INTO CURSOS VALUES ('')           --NOT WORKING DEFAULT--
INSERT INTO CURSOS (id_Curso) VALUES (5) --ERROR--

    --CREATE COLUMN NAME_COURSE--
    ALTER TABLE CURSOS
    ADD NAME_COURSE VARCHAR (50)

INSERT INTO CURSOS(NAME_COURSE) VALUES ('Fisica') --WORKING DEFAULT--
SELECT * FROM CURSOS

--pregunta 2.4--
ALTER TABLE NOTAS
ADD CONSTRAINT NOTACHK CHECK (NOTA > 0)

INSERT INTO NOTAS VALUES (19, 9, 12)
INSERT INTO NOTAS VALUES (19, 9, -12)

SELECT * FROM NOTAS

--pregunta 2.5--
ALTER TABLE PERSONAS 
ADD CONSTRAINT UC_NOMBRE UNIQUE (NOMBRE)

INSERT INTO PERSONAS VALUES ('Joan', 955244338)
INSERT INTO PERSONAS VALUES ('Joan', 955244337)

SELECT * FROM PERSONAS

--pregunta 2.6--
ALTER TABLE NOTAS
ADD FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)

ALTER TABLE NOTAS
ADD FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)

EXEC SP_HELP NOTAS
--pregunta 2.7--
INSERT INTO PERSONAS VALUES ('Carlos', 952999428)
INSERT INTO PERSONAS VALUES ('Pedro',  952999423)
 
INSERT INTO CURSOS (NAME_COURSE) VALUES ('Geografia')
INSERT INTO CURSOS (NAME_COURSE) VALUES ('Literatura')

INSERT INTO NOTAS VALUES (19, 9, 12)
INSERT INTO NOTAS VALUES (20, 8, 15)

SELECT * FROM CURSOS
SELECT * FROM NOTAS 
SELECT * FROM PERSONAS
-- pregunta 1.8--
INSERT INTO NOTAS VALUES (5, 8, 10)
