CREATE DATABASE EXAMCINFO2022
USE EXAMCINFO2022

---------------Pregunta 1-----------------------

CREATE TABLE ESTUDIANTES
( NOMBRE VARCHAR(30),
NOTA1 NUMERIC(10,0),
 NOTA2 NUMERIC(10,0),
 NOTA3 NUMERIC(10,0),
 NOTA4 NUMERIC(10,0)
)

INSERT ESTUDIANTES VALUES('Juan',11,12,12,13)
INSERT ESTUDIANTES VALUES('Ana',15,16,12,14)
INSERT ESTUDIANTES VALUES('Luis',8,9,13,11)
INSERT ESTUDIANTES VALUES('Deydith',11,10,15,9)
INSERT ESTUDIANTES VALUES('Jorge',10,11,13,10)

------------------------------------------------

--1.1--
SELECT * FROM ESTUDIANTES WHERE NOTA1 BETWEEN 13 AND 16 ORDER BY NOMBRE ASC
--1.2--
SELECT * FROM ESTUDIANTES WHERE NOMBRE LIKE '[AL]%'
--1.3--
SELECT *, (NOTA1 + NOTA2 + NOTA3 + NOTA4) / 4 AS AVERAGE FROM ESTUDIANTES ORDER BY AVERAGE DESC 
--1.4--
SELECT *, (NOTA1 + NOTA3) AS SUMA FROM ESTUDIANTES WHERE (NOTA1 + NOTA3) % 2 = 0 
SELECT NOMBRE, NOTA1, NOTA3, (NOTA1 + NOTA3) AS SUMA, CASE WHEN (NOTA1 + NOTA3) % 2 = 0 THEN 'SI' ELSE 'NO' END AS '¿ES PAR?' FROM ESTUDIANTES
--1.5--
SELECT *, (NOTA1 + NOTA2 + NOTA3 + NOTA4) / 4 AS AVERAGE FROM ESTUDIANTES WHERE (NOTA1 + NOTA2 + NOTA3 + NOTA4) / 4 >= 13 ORDER BY NOMBRE ASC
--1.6--
SELECT NOMBRE, NOTA2 FROM ESTUDIANTES ORDER BY NOTA2 DESC
--1.7--
SELECT * FROM ESTUDIANTES WHERE NOTA1 >= 14 AND NOTA2 >= 14
--1.8--
SELECT * FROM ESTUDIANTES WHERE NOTA4 % 2 = 1
--1.9--
    --EMPIEZA CON J--
    SELECT *, 
    (SELECT MAX(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)) AS J_MAX,
    CAST(ROUND((NOTA1 + NOTA2 + NOTA3 + NOTA4 - (SELECT MAX(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)))/3, 2, 1) AS DECIMAL (5,2)) AS J_AVG
    FROM ESTUDIANTES WHERE NOMBRE LIKE 'J%'
    --NO EMPIEZA CON J--
    SELECT *, 
    (SELECT MIN(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)) AS NOT_J_MIN,
    CAST(ROUND((NOTA1 + NOTA2 + NOTA3 + NOTA4 - (SELECT MIN(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)))/3, 2, 1) AS DECIMAL (5,2)) AS NOT_J_AVG
    FROM ESTUDIANTES WHERE NOMBRE NOT LIKE 'J%'
    
--UNIFICADO--
SELECT *, 
(SELECT MAX(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)) AS SPECIAL_NUMBER_CONDITIONAL,
CAST(ROUND((NOTA1 + NOTA2 + NOTA3 + NOTA4 - (SELECT MAX(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)))/3, 2, 1) AS DECIMAL (5,2)) AS AVERAGE_CONDITIONAL
FROM ESTUDIANTES WHERE NOMBRE LIKE 'J%' UNION ALL
SELECT *, 
(SELECT MIN(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)) AS SPECIAL_NUMBER_CONDITIONAL,
CAST(ROUND((NOTA1 + NOTA2 + NOTA3 + NOTA4 - (SELECT MIN(v) FROM (VALUES (NOTA1), (NOTA2), (NOTA3), (NOTA4) ) AS VALUE(v)))/3, 2, 1) AS DECIMAL (5,2)) AS AVERAGE_CONDITIONAL
FROM ESTUDIANTES WHERE NOMBRE NOT LIKE 'J%'
