SELECT TOP 10 * FROM ROBOTDIALER.ESCALABILIDAD
SELECT * FROM ROBOTDIALER.HORARIO
SELECT * FROM ROBOTDIALER.HORARIO_USUARIO

SELECT TOP 10 * FROM ROBOTDIALER.RESULTADOS

SELC
SELECT * FROM ROBOTDIALER.HORARIO_USUARIO WHERE
SELECT * FROM MONITOR.USUARIOS 

SELECT * FROM 
SELECT * FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO = 'ROL'
--INSERT INTO MONITOR.OPCIONES (ATRIBUTO, VALOR, TIPOATRIBUTO) VALUES ('GP','Gerente Proyecto','ROL')
--INSERT INTO MONITOR.OPCIONES (ATRIBUTO, VALOR, TIPOATRIBUTO) VALUES ('JT','Jefe Torre','ROL')
--INSERT INTO MONITOR.OPCIONES (ATRIBUTO, VALOR, TIPOATRIBUTO) VALUES ('GT','Gerente Torre','ROL')
--INSERT INTO MONITOR.OPCIONES (ATRIBUTO, VALOR, TIPOATRIBUTO) VALUES ('GD','Gerente Delivery','ROL')
--INSERT INTO MONITOR.OPCIONES (ATRIBUTO, VALOR, TIPOATRIBUTO) VALUES ('OC','Operador CECOM','ROL')



SELECT * FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO = 'AREA'
SELECT * FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO = 'ESCALABILIDAD_PERFIL'
SELECT * FROM MONITOR.USUARIOS WHERE NOMBRE = 'MIGUEL' AND IDAREA = 122

-- REGISTRO HORARIO_USUARIO
SELECT * FROM ROBOTDIALER.HORARIO_USUARIO
SELECT * FROM MONITOR.USUARIOS 
SELECT * FROM ROBOTDIALER.HORARIO WHERE DIA <> ''
SELECT * FROM MONITOR.CONF_REMEDY
-- REGISTRO HORARIO

-- DOM=1, LUN=2, MAR=3, MIE=4, JUE=5, VIE=6, SAB=7
--INSERT INTO ROBOTDIALER.HORARIO(HORARIO,HORA,DIA,MES,DIASEMANA) VALUES('HORARIO OFICINA 09:00 - 06:00','09:00-18:00','','1,2,3,4,5,6,7,8,9,10,11,12','1,2,3,4,5,6,7');
--INSERT INTO ROBOTDIALER.HORARIO(HORARIO,HORA,DIA,MES,DIASEMANA) VALUES('HORARIO FUERA OFICINA 18:01 - 05:59','18:01-05:59','','1,2,3,4,5,6,7,8,9,10,11,12','1,2,3,4,5,6,7');

//REGISTRO PERFIL ESCALABILIDAD
SELECT * FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO = 'ESCALABILIDAD_PERFIL'
--VALOR1 = NOMBRE DE PROYECTO, VALOR2 = ALP, ENTERO1 = MINUTO DE ESCALABILIDAD, ENTERO2 = PRIORIDAD
--INSERT INTO MONITOR.OPCIONES(ATRIBUTO,VALOR1,VALOR2,ENTERO1,ENTERO2,TIPOATRIBUTO) VALUES('Escalabilidad IM','','',0,1,'ESCALABILIDAD_PERFIL');


SELECT * FROM ROBOTDIALER.ESCALABILIDAD

-- REGISTRO ESCALABILIDAD

-- INSERT INTO ROBOTDIALER.ESCALABILIDAD(IDROL_AREA,TIPOESCALABILIDAD,IDPERFIL,ORDEN) VALUES(112,2,800,1);
-- INSERT INTO ROBOTDIALER.ESCALABILIDAD(IDROL_AREA,TIPOESCALABILIDAD,IDPERFIL,ORDEN) VALUES(113,2,800,1);
-- INSERT INTO ROBOTDIALER.ESCALABILIDAD(IDROL_AREA,TIPOESCALABILIDAD,IDPERFIL,ORDEN) VALUES(114,2,800,1);
-- INSERT INTO ROBOTDIALER.ESCALABILIDAD(PROYECTO,ALP,IDROL_AREA,TIPOESCALABILIDAD) VALUES('','',100,1);

SELECT * FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO = 'ESCALABILIDAD_PERFIL'

SELECT * FROM ROBOTDIALER.HORARIO_USUARIO

SELECT * FROM MONITOR.USUARIOS

SELECT RH.IDHORARIOUSUARIO, RH.IDAREA,  MOA.ATRIBUTO, * FROM (
SELECT RHU.IDAREA, RHU.IDHORARIOUSUARIO, CONCAT(MU.NOMBRE,' ', MU.APELLIDO) 'USER' FROM ROBOTDIALER.HORARIO_USUARIO RHU 
LEFT JOIN MONITOR.USUARIOS MU ON RHU.IDUSUARIO = MU.IDUSUARIO WHERE RHU.CANALES IS NULL
) AS RH LEFT JOIN MONITOR.OPCIONES MOA ON MOA.IDOPCION = RH.IDAREA 

SELECT * FROM ROBOTDIALER.HORARIO_USUARIO WHERE IDHORARIOUSUARIO IN (223,230)
SELECT * FROM MONITOR.USUARIOS
SELECT DISTINCT ATRIBUTO FROM MONITOR.OPCIONES WHERE TIPOATRIBUTO LIKE '%BLICO%'
SELECT MUSER.IDUSUARIO, MUSER.USUARIO, MUSER.NOMBRE, MUSER.CORREO, MOP.IDOPCION, MOP.ATRIBUTO, MUSER.SYSDATELAST FROM MONITOR.USUARIOS MUSER LEFT JOIN MONITOR.OPCIONES MOP ON MUSER.IDAREA = MOP.IDOPCION WHERE MOP.TIPOATRIBUTO = 'AREA' AND MOP.ATRIBUTO LIKE '%SAP%' AND MUSER.SYSDATELAST < '2022-10-03'
--CHANGE STATUS ESTADO = 0


